version: 2.0
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/php:7.1-node-browsers
    branches:
      only:
        - dev
    steps:
      - checkout
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Check current version of node
          command: node -v
      - run:
          name: Update Aptitude
          command: sudo apt-get update
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - run:
          name: Install LFTP
          command: sudo apt-get install lftp
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: Install theme Dependencies
          command: |
            cd themes/${theme}
            composer install -n --prefer-dist --no-dev
            yarn install --frozen-lockfile
            yarn build:production
      - run:
          name: Upload Theme
          command: |
            lftp -c "set sftp:auto-confirm yes; open -u ${username},${password} sftp://${hostname}:${port}; mirror -e -v -R --parallel=10 --exclude .git/ --exclude node_modules/ --exclude CHANGELOG.md --exclude CODE_OF_CONDUCT.md --exclude composer.json --exclude composer.lock --exclude package.json --exclude yarn.lock ./themes/${theme} domains/${site_name}/public_html/wp-content/themes/${theme}; quit";
      - run:
          name: Upload Plugins
          command: |
            lftp -c "set sftp:auto-confirm yes; open -u ${username},${password} sftp://${hostname}:${port}; mirror -e -v -R --parallel=10 --exclude .git/ --exclude node_modules/ --exclude CHANGELOG.md --exclude CODE_OF_CONDUCT.md --exclude composer.json --exclude composer.lock --exclude package.json --exclude yarn.lock ./plugins/ domains/${site_name}/public_html/wp-content/plugins; quit";
